### PR TITLE
ci: setup tests

### PR DESCRIPTION
**Pull request by milancermak**
This PR adds a GH action to run tests on push to main or a PR

### CODE REVIEW

**Comment by milancermak** [comment]
I guess it didn't run yet because it's not part of yours (origin) repo. Should run after merging, hopefully :) I adapted it a little from a setup I have in another repo.

**Comment by dhruvkelawala** [comment]
Your CI setup looks good but I would suggest that we should add more simple and real world tests. Wdyt? 

And yes, it will only trigger after I merge it.

**Comment by milancermak** [comment]
💯 for more tests, always :)

Though from my point of view, that's outside of the scope of this PR

**Comment by dhruvkelawala** [comment]
> 💯 for more tests, always :)
> 
> Though from my point of view, that's outside of the scope of this PR

I agree. Will add more test later.

**Comment by dhruvkelawala** [comment]
I just realised that you are using cairo-lang==0.7.1. We should use 0.8.0

**Comment by milancermak** [comment]
Yeah, I'm not using 0.8.0 yet for various reasons in my projects.

**Pull request merged**
